version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./requests/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  pgdata: