// 200 OK
PUT http://localhost:8189/items
Accept: application/json

{
    "id": "85471fbe-1dfc-4eac-a96b-df4ac85ede71",
    "title": "changed item",
    "price": 300
  }

###
// 400 Bad Request (Nothing to update)
PUT http://localhost:8189/items
Accept: application/json

{
"id": "7f862de8-fd9f-4160-95bb-df71e428017e"
}

###
// 400 Bad Request (No id)
PUT http://localhost:8189/items
Accept: application/json

{}

###
// 200 OK
PUT http://localhost:8189/items
Accept: application/json

{
  "id": "c5950b3a-cb8b-4671-9244-1a8fd0cda549",
  "title": "new item 90",
  "price": 10
}

###
// 200 OK
PUT http://localhost:8189/items
Accept: application/json

{
"id": "e86f6a29-7d77-4b1d-a1b3-bfdda8c745dc",
"title": "update test title"
}