// 201 Created
POST http://localhost:8189/items
Accept: application/json

{
"title": "new item 1",
"price": 10000
}

###
// 400 Bad Request ('title' and 'price' are required fields)
POST http://localhost:8189/items
Accept: application/json

{
"title": "new item 2"
}